parameters:
    ez_privacy_cookie_twig_extension: EzSystems\PrivacyCookieBundle\Twig\PrivacyCookieTwigExtension

services:
    ez_privacy_cookie.twig.extension:
        class: %ez_privacy_cookie_twig_extension%
        arguments:
            - @service_container
        calls:
            - [setCookieName, [%ez_privacy_cookie.cookie_name%]]
            - [setDays, [%ez_privacy_cookie.days%]]
        tags:
            - { name: twig.extension }
